### ISSUE TITLE
restifyErrorOptions.add() is not working

### ISSUE THREAD

**Issue by qburst-ranjith** [simonepri/restify-errors-options#4]
I would like to create some customized errors in a project, using restify(version 7.x) with custom error options. Now am able to create a customized error with parameters code and message using restify-errors. And I tried to create an error with more than two params using the restify-errors-option but it doesn't work.
is there any issue in this package now?

**Comment by simonepri** [comment]
The package is deprecated, sorry!

**Comment by qburst-ranjith** [comment]
Can you please suggest any solution to this issue?
